### ISSUE TITLE
OpenSuse Leap 42.3 - recover fails 

### ISSUE THREAD

**Issue by gdha** [gdha/rear-automated-testing#55]
### Logs are available at:
**https://gist.github.com/5b5b849279b22919507ee0f0aedff219**
````
+++ mkdir -p /mnt/local/.snapshots
+++ mount -t btrfs -o rw,relatime,space_cache -o subvol=@/.snapshots /dev/sda2 /mnt/local/.snapshots
mount: wrong fs type, bad option, bad superblock on /dev/sda2,
       missing codepage or helper program, or other error
````

@jsmeix as you are most familiar with SUSE (for obvious reasons) and fairly knowledge with btrfs file systems could you do me a favour and look at the logs which I provided in above link? I do not understand what went wrong. If you need more info please drop me a note.

Does `/usr/lib/snapper/installation-helper not executable may indicate an error with btrfs default subvolume setup for @/.snapshots/1/snapshot on /dev/sda2` ring any bell with you?

Thanks Gratien

**Comment by jsmeix** [comment]
On a fist glance (without reproducing anything) the local.conf in
https://gist.githubusercontent.com/gdha/5b5b849279b22919507ee0f0aedff219/raw/a0f78258d89b56d2dc4fa60a220f8b31f782a948/local.conf
is insufficient to recover an (open)SUSE btrfs default structure.

To recover an (open)SUSE btrfs default structure one must use
one of the usr/share/rear/conf/examples/SLE12*-btrfs-example.conf
as template - the one that matches the actual btrfs structure, cf.
https://github.com/rear/rear/issues/1368#issuecomment-302410707

In
https://gist.githubusercontent.com/gdha/5b5b849279b22919507ee0f0aedff219/raw/a0f78258d89b56d2dc4fa60a220f8b31f782a948/rear-client-recover.log
there is also about 10 lines before the mount error this message:
<pre>
2018-03-20 16:17:05.286694671 /usr/lib/snapper/installation-helper not executable may indicate an error with btrfs default subvolume setup for @/.snapshots/1/snapshot on /dev/sda2
</pre>

Regarding the SUSE-specific special /usr/lib/snapper/installation-helper see
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/examples/SLE12-SP1-btrfs-example.conf
and
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/examples/SLE12-SP2-btrfs-example.conf

As time permits I will reproduce a recovery on openSUSE Leap 42.3
to find out what the right local.conf is for that kind of btrfs structure.

**Comment by jsmeix** [comment]
@gdha 
don't worry when you do not understand SUSE's btrfs setup.
I think that's normal - at least also for me it is the same, cf.
https://github.com/rear/rear/pull/1435#issuecomment-319011579
<pre>
Always - really always - when I have to work with
that oversophisticated SUSE btrfs default structure
my poor mathematician's mind gets "knotted" :-(
</pre>

**Comment by gdha** [comment]
@jsmeix :+1: many thanks for reviewing the logs - I should have thought of it myself but I was struggling for such a long time before I got the ansible provisioning right I was eager to test it.

**Comment by gdha** [comment]
@jsmeix Successful restore executed - https://gist.github.com/6d8b2a1efe56a6ff85ac989911a3f590

**Comment by jsmeix** [comment]
Glad to see it is working!
