### ISSUE TITLE
Recover VM network interfaces are biosdevnames instead of eth0/eth1

### ISSUE THREAD

**Issue by gdha** [gdha/rear-automated-testing#6]
![image](https://cloud.githubusercontent.com/assets/888633/20263824/a52fffbc-aa68-11e6-94ea-1ae2e220b5e0.png)

**Comment by gdha** [comment]
See also issue https://github.com/rear/rear-workshop-osbconf-2016/issues/5

**Comment by gdha** [comment]
Fix it to add `KERNEL_CMDLINE="$KERNEL_CMDLINE net.ifnames=0"` to all rear workshop configuration files. Proven to work with **virtualbox**, however, still need to check if we do not break **libvirt** with it.

The rear-configs RPMs are created by https://github.com/rear/rear-workshop/blob/master/rear-configs/

**Comment by jsmeix** [comment]
FYI regarding "biosdevname" see also
https://github.com/rear/rear/issues/951

**Comment by gdha** [comment]
is fixed and proving to work well
